name: Deploy to AWS ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to ECR/ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t quiet-seoul .
          docker tag quiet-seoul:latest 781312897283.dkr.ecr.ap-northeast-2.amazonaws.com/quiet-seoul:latest

      - name: Push Docker image to ECR
        run: |
          docker push 781312897283.dkr.ecr.ap-northeast-2.amazonaws.com/quiet-seoul:latest